var annotated_dup =
[
    [ "ginga", null, [
      [ "UserData", "classginga_1_1UserData.html", "classginga_1_1UserData" ],
      [ "Composition", "classginga_1_1Composition.html", "classginga_1_1Composition" ],
      [ "Context", "classginga_1_1Context.html", "classginga_1_1Context" ],
      [ "Document", "classginga_1_1Document.html", "classginga_1_1Document" ],
      [ "Event", "classginga_1_1Event.html", "classginga_1_1Event" ],
      [ "Action", "structginga_1_1Action.html", "structginga_1_1Action" ],
      [ "GingaOptionData", "structginga_1_1GingaOptionData.html", "structginga_1_1GingaOptionData" ],
      [ "Formatter", "classginga_1_1Formatter.html", "classginga_1_1Formatter" ],
      [ "Media", "classginga_1_1Media.html", "classginga_1_1Media" ],
      [ "MediaSettings", "classginga_1_1MediaSettings.html", "classginga_1_1MediaSettings" ],
      [ "Object", "classginga_1_1Object.html", "classginga_1_1Object" ],
      [ "ParserElt", "classginga_1_1ParserElt.html", "classginga_1_1ParserElt" ],
      [ "ParserConnRole", "structginga_1_1ParserConnRole.html", "structginga_1_1ParserConnRole" ],
      [ "ParserLinkBind", "structginga_1_1ParserLinkBind.html", "structginga_1_1ParserLinkBind" ],
      [ "ParserState", "classginga_1_1ParserState.html", "classginga_1_1ParserState" ],
      [ "ParserSyntaxAttr", "structginga_1_1ParserSyntaxAttr.html", "structginga_1_1ParserSyntaxAttr" ],
      [ "ParserSyntaxElt", "structginga_1_1ParserSyntaxElt.html", "structginga_1_1ParserSyntaxElt" ],
      [ "Parser", "classginga_1_1Parser.html", null ],
      [ "ParserLua", "classginga_1_1ParserLua.html", null ],
      [ "PlayerPropertyInfo", "structginga_1_1PlayerPropertyInfo.html", "structginga_1_1PlayerPropertyInfo" ],
      [ "Player", "classginga_1_1Player.html", "classginga_1_1Player" ],
      [ "AnimInfo", "classginga_1_1AnimInfo.html", "classginga_1_1AnimInfo" ],
      [ "TransitionInfo", "structginga_1_1TransitionInfo.html", "structginga_1_1TransitionInfo" ],
      [ "PlayerAnimator", "classginga_1_1PlayerAnimator.html", "classginga_1_1PlayerAnimator" ],
      [ "GingaCefHandler", "classginga_1_1GingaCefHandler.html", "classginga_1_1GingaCefHandler" ],
      [ "GingaCefClient", "classginga_1_1GingaCefClient.html", "classginga_1_1GingaCefClient" ],
      [ "PlayerHTML", "classginga_1_1PlayerHTML.html", "classginga_1_1PlayerHTML" ],
      [ "PlayerImage", "classginga_1_1PlayerImage.html", "classginga_1_1PlayerImage" ],
      [ "PlayerLua", "classginga_1_1PlayerLua.html", "classginga_1_1PlayerLua" ],
      [ "PlayerRemote", "classginga_1_1PlayerRemote.html", "classginga_1_1PlayerRemote" ],
      [ "PlayerSigGen", "classginga_1_1PlayerSigGen.html", "classginga_1_1PlayerSigGen" ],
      [ "PlayerSvg", "classginga_1_1PlayerSvg.html", "classginga_1_1PlayerSvg" ],
      [ "PlayerText", "classginga_1_1PlayerText.html", "classginga_1_1PlayerText" ],
      [ "PlayerVideo", "classginga_1_1PlayerVideo.html", "classginga_1_1PlayerVideo" ],
      [ "Predicate", "classginga_1_1Predicate.html", "classginga_1_1Predicate" ],
      [ "Switch", "classginga_1_1Switch.html", "classginga_1_1Switch" ],
      [ "PlayerRemoteData", "classginga_1_1PlayerRemoteData.html", "classginga_1_1PlayerRemoteData" ],
      [ "WebServices", "classginga_1_1WebServices.html", "classginga_1_1WebServices" ]
    ] ],
    [ "Ginga", "classGinga.html", "classGinga" ],
    [ "GingaOptions", "structGingaOptions.html", "structGingaOptions" ]
];