#!/bin/sh -
# Copyright (C) 2014-2017 Free Software Foundation, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

test -n "$srcdir" || srcdir=`dirname "$0"`
test -n "$srcdir" || srcdir=.

ORIGDIR=`pwd`
cd $srcdir

PKGCONFIG=`which pkg-config`
if test -z "$PKGCONFIG"; then
  echo "*** pkg-config not found, please install it ***"
  exit 1
fi

AUTORECONF=`which autoreconf`
if test -z "$AUTORECONF"; then
  echo "*** No autoreconf found, please install it ***"
  exit 1
fi

test -f ./ChangeLog || touch ./ChangeLog

$AUTORECONF --force --install --verbose || exit $?
cd $ORIGDIR
