<ncl>
  <head/>
  <body>
    <port id="start1" component="time1"/>
    <port id="start2" component="time2"/>
    <media id="time1">
      <property name="width" value="50%"/>
      <property name="height" value="50%"/>
      <property name="background" value="red"/>
      <property name="focusIndex" value="0"/>
    </media>
    <media id="time2">
      <property name="bottom" value="0"/>
      <property name="right" value="0"/>
      <property name="width" value="50%"/>
      <property name="height" value="50%"/>
      <property name="background" value="green"/>
      <property name="focusIndex" value="1"/>
    </media>
  </body>
</ncl>
